title = "S3 Configuration"

[owner]
name = "Edmund Cape, Lucivia LLC"

[credentials]
S3_ACCESS_ID   = env.get('AWS_ACCESS_KEY_ID')
S3_SECRET_KEY  = env.get('AWS_SECRET_ACCESS_KEY')
S3_SESSION_TOKEN  = env.get('AWS_SESSION_TOKEN')

S3_REGION      = env.get('S3_REGION')
S3_REGION_NAME = env.get('S3_REGION_NAME')
S3_HOST_BASE   = env.get('S3_HOST_BASE')
S3_HOST_BUCKET = env.get('S3_HOST_BUCKET')
S3_BUCKET_NAME = env.get('S3_BUCKET_NAME')


        return self.session.client(
            's3',
            config=client_config,
            region_name=self.app.config['S3_REGION_NAME'],
            endpoint_url=self.app.config['S3_HOST_BASE'],

            aws_access_key_id=self.app.config['AWS_ACCESS_KEY_ID'],
            aws_secret_access_key=self.app.config['AWS_SECRET_ACCESS_KEY'],

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-env-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-env-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: S3_REGION
              value: "US"
            - name: S3_REGION_NAME
              value: "sfo3"
            - name: S3_HOST_BASE
              value: "https://sfo3.digitaloceanspaces.com"
            - name: S3_HOST_BUCKET
              value: "https://luci-space.sfo3.digitaloceanspaces.com"
            - name: S3_BUCKET_NAME
              value: "luci-space"
